headersOrigin = "config"
redirectsOrigin = "config"
plugins = []
functionsDirectory = "/Users/matt/Desktop/Nu-food-logger/frontend/netlify/functions"
functionsDirectoryOrigin = "config-v1"

[functions]

[functions."*"]

[build]
publish = "/Users/matt/Desktop/Nu-food-logger/frontend/frontend/build"
publishOrigin = "config"
commandOrigin = "config"
base = "/Users/matt/Desktop/Nu-food-logger/frontend"
command = "cd frontend && npm run build"
functions = "/Users/matt/Desktop/Nu-food-logger/frontend/netlify/functions"

[build.environment]
NODE_VERSION = "18"

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[headers]]
for = "/*"

[headers.values]
X-Frame-Options = "DENY"
X-XSS-Protection = "1; mode=block"
X-Content-Type-Options = "nosniff"
Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
for = "/static/*"

[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/sw.js"

[headers.values]
Cache-Control = "public, max-age=0, must-revalidate"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]